class ProjectDependencies {
    static final String springBootStarter = "org.springframework.boot:spring-boot-starter"
    static final String springBootWeb = "org.springframework.boot:spring-boot-starter-web"
    static final String jwt = "io.jsonwebtoken:jjwt:0.11.5"
    static final String springBootStarterSecurity = "org.springframework.boot:spring-boot-starter-security"
    static final String gson = "com.google.code.gson:gson:2.12.1"
    static final String junit = "org.junit.jupiter:junit-jupiter:5.9.1"
}