doc:
  web:
    api:
      #Defines which cross origin urls can access what link
      crossOrigin:
        "/**":
          - origin: http://localhost:4200

          - origin: http://localhost:8080
      #Defines all resources accessible by anyone without role or authentication needed
      whitelist:
        - "/auth/login"
        - "/error"
        - "/public/**"
        - "/favicon.ico"
  git:
    repositories:
      - id: "repo1"
        path: temp/git/repo1
      - id: "repo2"
        path: temp/git/repo2
      #- name: "Read only Repo"
      #  path: temp/git/readOnlyRepo
      # readOnly: true
      # dbStorage: temp/git/readOnlyRepoDB