doc:
  web:
    api:
      #Defines which cross origin urls can access what link
      crossOrigin:
        - origin: "http://localhost:8080"
          path: "/**"
        - origin: "http://localhost:4200"
          path: "/**"
  git:
    repositories:
      - id: "repo1"
        path: temp/git/repo1
      - id: "repo2"
        path: temp/git/repo2
      #- name: "Read only Repo"
      #  path: temp/git/readOnlyRepo
      # readOnly: true
      # dbStorage: temp/git/readOnlyRepoDB